### ISSUE TITLE
AI 모델을 통한 음성 추출

### ISSUE THREAD

**Issue by ryunji** [dlrunner/speech_diarization#6]
## 🍎기능 이름
[Feat]  음성 녹음 기능
## 🍎기능 요약 설명
- 단어 '녹음'을 말하면 음성을 녹음하고, '중단'을 말하면 녹음 파일을 저장한다.
## 🎯할일 목록
- 1. 실시간 음성 자막 출력
- 2. 음성 녹음
- 3. 음성 및 텍스트 파일 추출

**Comment by wendywoo95** [comment]
마지막 오디오 청크에 대한 '오디오, 텍스트'만 저장이 되고 있는데, 전체 오디오에 대한 '오디오, 텍스트'를 저장하도록 윤지님이 수정 중
